COINMARKETCAP_BASE_URL = "https://pro-api.coinmarketcap.com"
UNISWAP_BASE_URL = "https://app.uniswap.org"
MATCHA_BASE_URL = "https://matcha.xyz/tokens"
DEXSCREENER_BASE_URL = "https://api.dexscreener.com"
BINGX_BASE_URL = "https://open-api.bingx.com"
