"""add all fields

Revision ID: 80b26c5f972a
Revises: 
Create Date: 2025-04-05 16:18:31.650197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80b26c5f972a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bingx',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sumbol', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('chain', sa.String(), nullable=False),
    sa.Column('token_address', sa.String(), nullable=False),
    sa.Column('logo', sa.String(), nullable=False),
    sa.Column('signal', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mexc',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sumbol', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('chain', sa.String(), nullable=False),
    sa.Column('token_address', sa.String(), nullable=False),
    sa.Column('logo', sa.String(), nullable=False),
    sa.Column('signal', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mexc')
    op.drop_table('bingx')
    # ### end Alembic commands ###
