"""update_fields

Revision ID: 87e4ba3a303b
Revises: e9c6e0342f0a
Create Date: 2025-04-09 01:45:38.446554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87e4ba3a303b'
down_revision: Union[str, None] = 'e9c6e0342f0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=True),
    sa.Column('subscription_active', sa.Boolean(), nullable=False),
    sa.Column('last_payment_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_id')
    )
    op.create_table('chains',
    sa.Column('chain', sa.String(), nullable=False),
    sa.Column('token_address', sa.String(), nullable=False),
    sa.Column('mexc_id', sa.Integer(), nullable=True),
    sa.Column('bingx_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bingx_id'], ['bingx.id'], ),
    sa.ForeignKeyConstraint(['mexc_id'], ['mexc.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chains')
    op.drop_table('users')
    # ### end Alembic commands ###
