"""new migrate

Revision ID: f10a0561a70e
Revises: 87e4ba3a303b
Create Date: 2025-04-10 00:18:15.120077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f10a0561a70e'
down_revision: Union[str, None] = '87e4ba3a303b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bingx', 'token_address')
    op.drop_column('bingx', 'chain')
    op.drop_column('mexc', 'token_address')
    op.drop_column('mexc', 'chain')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mexc', sa.Column('chain', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mexc', sa.Column('token_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('bingx', sa.Column('chain', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('bingx', sa.Column('token_address', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
